language: java
jdk:
- oraclejdk8
sudo: false
# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

# script for build and release via Travis to Bintray
script: gradle/buildViaTravis.sh

# Code coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  
env:
  global:
  - secure: "WP1xTcv1Ti9vozsZSZYTPxi2iW4KVW9MmlZaQgnHvrDZRo+Z/VvugG1Ww49TY9qv/xd3d+sw8SuRu/yBP/KOAeaQLJ6mjeVcWKUngIJv70/mfp5d4ErnU0D7ntzyi00K9Q0C7cKO3sxaPAynGHeVAFKopjaXxQT4171QFoUZNq0="
  - secure: "pNrV8dNdQMgZcH4EtrG15tPWwDM2kOTEdMumuU8c7xU20pXvQrYuoi4XEt3bdROz772uFuqGhxbxGjoXJiqg2DxIrYHVgbCJzTiifIiW/19poqplNNLfSPwmE7u4YXLgKXKPLs4SO1LsFmPkn5KoopCTChbqJYnGXLj2EtU7wcQ="
  - secure: "J38VYI7m7sIGJtM+xdkuSZ5YoROjrM8Be74JDLHs+MH22n6uqupoRRWUAkSP4gCMA/kp7WKNFJsv+6OBUCxSdMUVA2x7dFJ5ocV9zAZuPXTBaR9k/cWmOrKg7ih23LntQbp/6vBoGMv+qwJ0HuFZefh0lSRfBvbJ+BYROxgWJiI="
  - secure: "O7JOWfyyKOBoXCM/P7kHE/72rPcdlweW14f22G+CzD8+5WYaVch4XtQiXvLNvw6K/xNn5xFSGtTdBYPXXENrhxKZcRkNjfxAMCZO5HwtPeRwLdem1IxdoJkkU1iinJDqLRVy1KFU3pzSH+6SINtpLKZZe3Zc1bCZ8ECxlsaV4rg="